#!/usr/bin/env python

import ftp_common as fc
import sys
from ftp_common import connection as conn
from ftplib import FTP, all_errors

def download_binary():
    fc.clear_files()
    fc.setup_files()
    try:
        ftp = FTP()
        ftp.connect(conn['host'], conn['port'])
        ftp.login(conn['user'], conn['passwd'])
        ftp.cwd(fc.ftp_work_folder)
        ftp.retrbinary('RETR ' + fc.ftp_work_folder + '/' + fc.bin_dest_file, open(fc.junk_file,'wb').write)
        fc.check_transfer(fc.junk_file, fc.ftp_work_folder + '/' + fc.bin_dest_file)
        ftp.quit()
        return 0

    except all_errors, inst:
        print "EXCEPTION:", type(inst)
        print "EXCEPTION:", inst
        return -1
       
if(download_binary() == 0):
    print sys.argv[0], "PASSED"
    sys.exit(0)
else:
    print sys.argv[0], "FAILED"
    sys.exit(1)
