#!/usr/bin/env python

import ftp_common as fc
import sys
from ftp_common import connection as conn
from ftplib import FTP, all_errors

def upload_ascii():
    fc.clear_files()
    fcopy = open(fc.ascii_copy_file, "rb")
    try:
        ftp = FTP()
        ftp.connect(conn['host'], conn['port'])
        ftp.login(conn['user'], conn['passwd'])
        ftp.cwd(fc.ftp_work_folder)
        ftp.storbinary('STOR ' + fc.ascii_dest_file, fcopy)
        fc.check_transfer(fc.ascii_copy_file, fc.ftp_work_folder + '/' + fc.ascii_dest_file)
        ftp.quit()
        return 0

    except all_errors, inst:
        print "EXCEPTION:", type(inst)
        print "EXCEPTION:", inst
        return -1
       
        
if(upload_ascii() == 0):
    print sys.argv[0], "PASSED"
    sys.exit(0)
else:
    print sys.argv[0], "FAILED"
    sys.exit(1)
